file:
  upload:
    extension:
      wav: wav|aif|mp3|mid|mp2|wam|ogg|m4a|aac
      train: doc|docx|hwp|pdf|txt
    path:
      train: D:/e2e/upload/sgsas_train/upload/train
      test: D:/e2e/upload/sgsas_train/upload/test
      meet: D:/e2e/upload/sgsas_train/upload/meet
      temp: D:/e2e/upload/sgsas_train/upload/temp
spring:
  servlet:
    multipart:
      location: c:\temp  #톰켓 temp 로 변경 필요
  datasource:
    hikari:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://192.168.0.233:3307/SGSAS?serverTimezone=UTC
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://192.168.0.239:33342/MEETING?serverTimezone=UTC    # steel-pc
      password: meet_pass
      username: meet_user
stt:
  service:
    manager:
      ip: localhost
      port: 8988
      use: false
  url: http://192.168.0.252:8987/was/stt_diarization
  alternate: 
    curl:
#      size: 10000
      size: 500000000
      command: cmd, /c, curl
      quote: double                                   # double quote for curl -H "accept: application/json"
  confidence: false
  
summary:
  url: http://192.168.0.30:7000/summarize
  url2: http://192.168.0.30:7000/summarize2
  url3: http://192.168.0.252:7000/summ/timestamp?filename=asd
train:
  url: http://192.168.0.249:8989
  project_id: 6674cdf7573bb67ec1a50565
ffmpeg:
  ffmpeg:
    path: C:\ProgramData\chocolatey\lib\ffmpeg-full\tools\ffmpeg\bin\ffmpeg.exe
  ffprobe:
    path : C:\ProgramData\chocolatey\lib\ffmpeg-full\tools\ffmpeg\bin\ffprobe.exe
task:
  sound:
    train:
      max: 1
    test:
      max: 1
    no_data_sleep: 60
    urls: >
      http://192.168.0.249:8987/was/stt_diarization_comp
  summary:
    max: 1  
    no_data_sleep: 60
